#! /bin/bash
cd srv
source venv/bin/activate
pip install -r requirements.txt
cd venv
git clone git://github.com/gvnn3/PCS.git
cd PCS
cp ../../pcs-linux.patch .
git apply pcs-linux.patch
../bin/python2 setup.py config
../bin/python2 setup.py install


