#!/usr/bin/env python

#  Copyright 2017 Jonathan Anderson
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

"""
cogui: CADETS/OPUS graphical user interface

Usage:
    cogui serve [--port=PORT] [--host=HOST] [options]

Commands:
    serve         Expose data through a local Web server

Options:
    -p,--port=PORT            TCP port to serve content on [default: 5000]
    -h,--host=HOST            Host IP of web server [default: 127.0.0.1]

    --db-url=URL              Neo4j URL [default: bolt://localhost]
    --db-username=USERNAME    Neo4j username [default: neo4j]
    --db-password=PASSWORD    Neo4j password [default: opus]
"""

import docopt
import neo4j.v1
import sys

arguments = docopt.docopt(__doc__)

if arguments['serve']:
    import webapp
    try: port = int(arguments['--port'])
    except ValueError:
        sys.stderr.write("Invalid port number: '%s'\n" % arguments['--port'])
        sys.exit(1)

    try:
        host = arguments['--host']
    except ValueError:
        sys.stderr.write("Invalid host: '%s'\n" % arguments['--host'])
        sys.exit(1)

    db_driver = neo4j.v1.GraphDatabase.driver(
        arguments['--db-url'],
        auth = neo4j.v1.basic_auth(arguments['--db-username'],
                                   arguments['--db-password']),
    )

    app = webapp.create_app(db_driver)
    app.run(host = host, port = port, debug = True)
