#!/usr/bin/env python

#  Copyright 2017 Jonathan Anderson
#
#    Licensed under the Apache License, Version 2.0 (the "License");
#    you may not use this file except in compliance with the License.
#    You may obtain a copy of the License at
#
#        http://www.apache.org/licenses/LICENSE-2.0
#
#    Unless required by applicable law or agreed to in writing, software
#    distributed under the License is distributed on an "AS IS" BASIS,
#    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#    See the License for the specific language governing permissions and
#    limitations under the License.

"""
cogui: CADETS/OPUS graphical user interface

Usage:
    cogui serve [--port=PORT] [--synthetic-data=FILE]

Commands:
    serve         Expose data through a local Web server

Options:
    -p,--port=PORT            TCP port to serve content on [default: 5000]
    -s,--synthetic-data=FILE  JSON file of synthetic graph data
"""

import docopt
import sys

arguments = docopt.docopt(__doc__)

if arguments['serve']:
    import webapp
    try: port = int(arguments['--port'])
    except ValueError:
        sys.stderr.write("Invalid port number: '%s'\n" % arguments['--port'])
        sys.exit(1)

    filename = arguments['--synthetic-data']
    if filename:
        import synth_data
        graph_data, query_connections = synth_data.load(open(filename, 'r'))

    else:
        import mock_data
        graph_data = (mock_data.nodes, mock_data.edges)
        query_connections = mock_data.get_connections

    app = webapp.create_app(graph_data, query_connections)
    app.run(port = port, debug = True)
